map: remove reference to OviHybrid tile service
Change the default value of the --service argument from OviHybrid to
MicrosoftSat. OviHybrid was removed a few years ago, so attempting to run
mp_tile.py as a script results in the following error:

Traceback (most recent call last):
  File "/nix/store/zs9s8ncp22dpyvnhn858rpvpsch921g3-MAVProxy-1.8.53/bin/.mp_tile.py-wrapped", line 644, in <module>
    mt = MPTile(debug=opts.debug, service=opts.service,
  File "/nix/store/zs9s8ncp22dpyvnhn858rpvpsch921g3-MAVProxy-1.8.53/bin/.mp_tile.py-wrapped", line 208, in __init__
    raise TileException('unknown tile service %s' % service)
__main__.TileException: unknown tile service OviHybrid