Make wxPython optional for basic mavproxy operations.
A previous change was checking for "CYGWIN" in platform.system() which
is a fine fix but insufficient for my platform.  My platform is not cygwin
(it is a very stripped down linux) but still can't run wxPython.  So
as a cleaner way for checking for this problem I added has_wxpython to
mp_util.  This bool will be True on platforms where wxPython could be
found.

I also fixed an error in idle callbacks for these platforms:

Without this change on platforms without wxPython the following
failures would occur, because self.menu_added... would not be initialized
in the constructor.  My fix flips the order of comparisons so we
check for the console or map module _first_ and shortcircut out before
noticing that self.menu_added... is empty.

AttributeError: 'RallyModule' object has no attribute 'menu_added_console'
Traceback (most recent call last):
  File "/home/kevinh/development/drone/MAVProxy/MAVProxy/mavproxy.py", line 862, in periodic_tasks
    m.idle_task()
  File "/home/kevinh/development/drone/MAVProxy/MAVProxy/modules/mavproxy_fence.py", line 52, in idle_task
    if not self.menu_added_console and self.module('console') is not None:
AttributeError: 'FenceModule' object has no attribute 'menu_added_console'
Traceback (most recent call last):
  File "/home/kevinh/development/drone/MAVProxy/MAVProxy/mavproxy.py", line 862, in periodic_tasks
    m.idle_task()
  File "/home/kevinh/development/drone/MAVProxy/MAVProxy/modules/mavproxy_rally.py", line 47, in idle_task
    if not self.menu_added_console and self.module('console') is not None:
AttributeError: 'RallyModule' object has no attribute 'menu_added_console'
Traceback (most recent call last):
  File "/home/kevinh/development/drone/MAVProxy/MAVProxy/mavproxy.py", line 862, in periodic_tasks
    m.idle_task()
  File "/home/kevinh/development/drone/MAVProxy/MAVProxy/modules/mavproxy_fence.py", line 52, in idle_task
    if not self.menu_added_console and self.module('console') is not None:
AttributeError: 'FenceModule' object has no attribute 'menu_added_console'