MAVExplorer.py: correct printing of exceptions, catch shlex exception
the exception fixes are similar to those already made in mavproxy.py - change to the way we invoke format_exception

shlex raises an exception on bad input, and not catching it makes the MAVExplorer session no-longer-responsive.

param LOG_BACKEND_TYPE\
MAV> No escaped character
Traceback (most recent call last):
  File "/home/pbarker/.local/lib/python3.10/site-packages/MAVProxy-1.8.50-py3.10.egg/EGG-INFO/scripts/MAVExplorer.py", line 984, in process_stdin
  File "/usr/lib/python3.10/shlex.py", line 315, in split
    return list(lex)
  File "/usr/lib/python3.10/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib/python3.10/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.10/shlex.py", line 210, in read_token
    raise ValueError("No escaped character")
ValueError: No escaped character